Resources:
  BlogApiFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: main
      Runtime: go1.x
      CodeUri: .
      Events:
        Root:
          Type: Api
          Properties:
            Path: /
            Method: GET
        PagesById:
          Type: Api
          Properties:
            Path: /v1/posts/{id}
            Method: ANY
        Pages:
          Type: Api
          Properties:
            Path: /v1/posts
            Method: ANY
